import { CurrencyData, CountryCode, VatRates } from '@/types/invoice';

export const CURRENCY_BY_COUNTRY: CurrencyData = {
  "United Kingdom": "GBP",
  "Ireland": "EUR",
  "Germany": "EUR",
  "France": "EUR",
  "Italy": "EUR",
  "Spain": "EUR",
  "Portugal": "EUR",
  "Netherlands": "EUR",
  "Belgium": "EUR",
  "Luxembourg": "EUR",
  "Austria": "EUR",
  "Greece": "EUR",
  "Cyprus": "EUR",
  "Malta": "EUR",
  "Finland": "EUR",
  "Estonia": "EUR",
  "Latvia": "EUR",
  "Lithuania": "EUR",
  "Slovakia": "EUR",
  "Slovenia": "EUR",
  "Croatia": "EUR",
  "Czechia": "CZK",
  "Poland": "PLN",
  "Hungary": "HUF",
  "Romania": "RON",
  "Bulgaria": "BGN",
  "Denmark": "DKK",
  "Sweden": "SEK",
  "Norway": "NOK",
  "Switzerland": "CHF",
  "Iceland": "ISK",
  "Serbia": "RSD",
  "Bosnia and Herzegovina": "BAM",
  "North Macedonia": "MKD",
  "Albania": "ALL",
  "Montenegro": "EUR",
  "Kosovo": "EUR",
  "Moldova": "MDL",
  "Ukraine": "UAH",
  "Georgia": "GEL",
  "Turkey": "TRY",
  "Andorra": "EUR",
  "Monaco": "EUR",
  "San Marino": "EUR",
  "Liechtenstein": "CHF",
  "Vatican City": "EUR"
};

export const CC: CountryCode = {
  "United Kingdom": "UK",
  "Ireland": "IE",
  "Germany": "DE",
  "France": "FR",
  "Italy": "IT",
  "Spain": "ES",
  "Portugal": "PT",
  "Netherlands": "NL",
  "Belgium": "BE",
  "Luxembourg": "LU",
  "Austria": "AT",
  "Greece": "GR",
  "Cyprus": "CY",
  "Malta": "MT",
  "Finland": "FI",
  "Estonia": "EE",
  "Latvia": "LV",
  "Lithuania": "LT",
  "Slovakia": "SK",
  "Slovenia": "SI",
  "Croatia": "HR",
  "Czechia": "CZ",
  "Poland": "PL",
  "Hungary": "HU",
  "Romania": "RO",
  "Bulgaria": "BG",
  "Denmark": "DK",
  "Sweden": "SE",
  "Norway": "NO",
  "Switzerland": "CH",
  "Iceland": "IS"
};

export const VAT_RATES: VatRates = {
  UK: [0, 5, 20],
  DE: [0, 7, 19],
  FR: [0, 5.5, 10, 20],
  IT: [0, 5, 10, 22],
  ES: [0, 10, 21],
  NL: [0, 9, 21],
  BE: [0, 6, 12, 21],
  SE: [0, 6, 12, 25],
  DK: [0, 25],
  FI: [0, 10, 14, 24],
  IE: [0, 9, 13.5, 23],
  PL: [0, 5, 8, 23],
  CZ: [0, 12, 21],
  PT: [0, 6, 13, 23],
  AT: [0, 10, 13, 20],
  GR: [0, 6, 13, 24],
  HU: [0, 5, 18, 27],
  LU: [0, 3, 8, 17],
  LT: [0, 9, 21],
  LV: [0, 12, 21],
  EE: [0, 9, 22],
  RO: [0, 5, 9, 19],
  BG: [0, 9, 20],
  SI: [0, 9.5, 22],
  SK: [0, 10, 20],
  HR: [0, 5, 13, 25],
  CY: [0, 5, 9, 19],
  MT: [0, 5, 7, 18],
  NO: [0, 12, 25],
  CH: [0, 2.6, 3.8, 8.1],
  IS: [0, 11, 24]
};



